apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: voting-app-d

spec:
  #type: LoadBalancer
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    name: redis-pod
    app: voting-app-d
