apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    app: voting-app-d
spec:
  replicas: 2
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: voting-app-d
    spec:
      containers:
        - name: redis-container
          image: redis:latest
          ports:
            - containerPort: 6379
  selector:
    matchLabels:
      name: redis-pod
      app: voting-app-d
