apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    name: result-app
    app: voting-app-d
spec:
  replicas: 2
  template:
    metadata:
      name: result-pod
      labels:
        name: result-pod
        app: voting-app-d
    spec:
      containers:
        - name: result-container
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      name: result-pod
      app: voting-app-d
