apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: voting-app-d
spec:
  #type: LoadBalancer
  ports:
     - targetPort: 80
       port: 80
  selector:
    name: voting-pod
    app: voting-app-d
